name: 游 Deploy autom치tico a Bluehost (FTP)

on:
  push:
    branches:
      - main  # Cambi치 si tu rama principal es otra (ej: master)

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 游닌 Descargar c칩digo desde GitHub
        uses: actions/checkout@v3

      - name: 游 Subir archivos a Bluehost fuera de la ra칤z
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ftp.cvj.hbq.mybluehost.me
          username: ${{ secrets.FTP_USERNAME }}         # = richard@habitareinmobiliaria.com.py
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          server-dir: ../../../../../public_html/ventas/
          local-dir: ./
          dangerous-clean-slate: true
          exclude: |
            **/.git*
            **/.github/**
            **/.vscode/**
            **/node_modules/**
            **/*.log
            README.md
            deploy.yml
